---
params:
  section: "abc"
  pg: "abc"
  var: "abc"
title: "`r paste0(params$section,': ',params$pg)`"
output: 
 html_document: 
   self_contained: no
   mathjax: null
   highlight: null
   fig_width: 10
   theme: null
   template: "../../CCO_template_html.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F,message = F)

require(readxl)
require(data.table)
require(dplyr)
require(ggplot2)
require(reactable)
require(htmltools)
require(tippy)

age_grp<-NULL

stem<-"W:/CCO-WORKING-FS/Projects/big ask survey/analysis/survey data/cleaned data/"

dk_vals<-c("I dont know","I dont want to say","Other","I am not sure")

search_str<-"parents_clean"

target_vals<-c("Very unlikely","Unlikely","Fairly unlikely","Yes")

col1<-"%"

table_f<-function(x,df_use=df){
  
  x<-unlist(strsplit(x,"[|]"))
  
  reg<-paste0("^",x,"$")
  
  reg_string<-paste0("^id$|parents_clean|wt|",paste0(reg,collapse="|"))
  hap_col<-names(df_use)[grepl(reg_string,names(df_use))]
  
  hap_col<-hap_col[!grepl("dont want to",hap_col)]
  
  df_la<-melt(df_use[!q4_parents_clean %in% dk_vals][,..hap_col],id.vars = c("id",x,"wt"))[,variable:=plyr::mapvalues(variable,
                                                                                                                            q_lookup$var,
                                                                                                                            q_lookup$label)]
  
  df_la[,value:=ifelse(value %in% target_vals,1,0)
  ]
}

source("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/scripts/markdown_functions.R",local=knitr::knit_global())

pal<-RColorBrewer::brewer.pal(7,"Reds")

```

<link rel="stylesheet" href="../../styles.css" type="text/css" />

```{r}

df<-readRDS("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/survey data/final data/9-17_weighted.rds")

#imd<-fread(file="W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/imd2019lsoa.csv")[Measurement=="Decile"]

imd<-fread(file="W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/idaci.csv")

df<-df[,id:=paste0(id,survey)
       ][!q4_parents_clean %in% dk_vals
         ][,q4_parents_clean_2:=ifelse(q4_parents_clean %in% c("Fairly likely","Very likely","Likely"),"Yes","No")]

q_lookup<-data.table(var=c("q4_parents_clean","q4_parents_clean_2"),label=c("Children think its unlikely they will have a better life than their parents","Children think its likely they will have a better life than their parents"))

q_lookup_hap<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_happy_q_lookup.csv")
q_lookup_hap$var<-gsub("Option ","q1_happy_",q_lookup_hap$var)

q_lookup_imp<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_important_q_lookup.csv")
q_lookup<-q_lookup[!grepl("dont want",var)]

q_lookup_worry<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_worry_q_lookup.csv")
q_lookup_worry<-q_lookup_worry[!grepl("dont want",var)]

```

```{r, child='W:/CCO-WORKING-FS/Projects/big ask survey/analysis/markdown/child docs/navigation_child_doc.rmd'}


```

<script src="extra_js.js"></script>

<h3>Key stats</h3>
<div class="stat-boxes">

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

</div>


<h3> About this data</h3>

INTRO TEXT

<h3>Do children think it is likely they will have a better life than their parents?</h3>

```{r}
dat<-df[!q4_parents_clean %in% dk_vals
        ][,q4_parents_clean:=ifelse(q4_parents_clean %in% dk_vals,NA,
                                    ifelse(q4_parents_clean %in% c("Fairly likely","Very likely","Likely"),"Likely",
                                           ifelse(q4_parents_clean %in% target_vals,"Unlikely","Neither likely/unlikely")))
  ][,.(c=sum(wt)),by=.(q4_parents_clean)][,perc:=round(c/sum(c),2)*100,]

ggplot(dat,
       aes(x=reorder(q4_parents_clean,perc),y=perc))+
  geom_col(fill="light blue",colour="grey20")+coord_flip()+geom_text(aes(label=paste0(perc,"%")),hjust=1)+
  theme_bw()+xlab("How likely ist it you will have\na better life than your parents?\n")+ylab("% of 9-17 yr olds")

```