---
title: "Do children think they will have a better life than their parents?"
output: 
 html_document: 
   self_contained: no
   theme: null
   mathjax: null
   highlight: null
   template: "../../CCO_template_html.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

<link rel="stylesheet" href="../../styles.css" type="text/css" />

<a href="../../index.html">Home</a></li>

<h3>Overall Rates</h3>


<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_overall.html">
<h3 class="list_header">Do children think they will have a better life than their parents?</h3></a>
</div>


<h3>How is this different for sub-groups of children?</h3>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_child_chars.html">
<h3 class="list_header">Demographic groups</h3></a>
</div>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_disad.html">
<h3 class="list_header">Vulnerable children</h3></a>
</div>

<h3>How is this different based on where children live?</h3>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_map.html">
<h3 class="list_header">Overall local area rates</h3></a>
</div>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_area_chars.html">
<h3 class="list_header">Differences by local area characteristics</h3></a>
</div>

<h3>How is this different based on where children go to school?</h3>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_school.html">
<h3 class="list_header">School characteristics</h3></a>
</div>

<h3>How is this different based on children's happiness now?</h3>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_happiness.html">
<h3 class="list_header">Correlations with happiness now</h3></a>
</div>

<h3>How is this different based on children's future priorities?</h3>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_important.html">
<h3 class="list_header">Correlations with future priorities</h3></a>
</div>

<h3>How is this different based on children's worries about the future?</h3>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_worry.html">
<h3 class="list_header">Correlations with worries about the future</h3></a>
</div>

<h3>Multivariate analysis</h3>

<div class="topic_navList">
<a class="meta_navList_link" href="9-17_parents_regression.html">
<h3 class="list_header">Regression analysis</h3></a>
</div>