---
params:
  section: "abc"
  pg: "abc"
  var: "abc"
title: "`r paste0(params$section,': ',params$pg)`"
output: 
 html_document: 
   self_contained: no
   mathjax: null
   highlight: null
   fig_width: 10
   theme: null
   template: "../../CCO_template_html.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F,message = F)

require(readxl)
require(data.table)
require(dplyr)
require(ggplot2)
require(reactable)
require(htmltools)
require(tippy)

stem<-"W:/CCO-WORKING-FS/Projects/big ask survey/analysis/survey data/cleaned data/"

target_vals<-"Yes"

dk_vals<-""

col1<-"% of children that think x is important..."

search_str<-"important_"

table_f<-function(x,df_use=df){
  
  x<-unlist(strsplit(x,"[|]"))
  
  reg<-paste0("^",x,"$")
  
  reg_string<-paste0("^id$|important_|wt|",paste0(reg,collapse="|"))
  hap_col<-names(df_use)[grepl(reg_string,names(df_use))]
  
  hap_col<-hap_col[!grepl("dont",hap_col)]
  
df_la<-melt(df_use[,..hap_col],id.vars = c("id",x,"wt"))[,variable:=plyr::mapvalues(variable,
                                                                                    q_lookup$var,
                                                                                    q_lookup$label)]

df_la[,value:=ifelse(value %in% target_vals,1,0)
           ]
}

source("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/scripts/markdown_functions.R",local=knitr::knit_global())
  
```

<link rel="stylesheet" href="../../styles.css" type="text/css" />

```{r}

df<-readRDS("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/survey data/final data/6-8_weighted.rds")


#imd<-fread(file="W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/imd2019lsoa.csv")[Measurement=="Decile"]

imd<-fread(file="W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/idaci.csv")

df<-df[!dfe_phase %in% "Secondary"
       ][,id:=paste0(id,survey)
         ][,dem_gender_clean:=plyr::mapvalues(dem_gender_clean,
                                              c("Boy","Girl"),c("Male","Female"))
           ][,any_mh:=ifelse(`dem_support_A healthcare worker`=="Yes","Yes","No")
             ][`q3_important_I dont want to say` %in% c(NA,"No") &
                 `q3_important_I dont know` %in% c(NA,"No") &
                 `q3_important_I dont know what will be important` %in% c(NA,"No")
               ]

q_lookup<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\6-8_important_q_lookup.csv")


q_lookup_hap<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\6-8_happy_q_lookup.csv")

age_grp<-"6-8"


 reg_string<-"^id$|feel.*_"
 
 hap_col<-names(df)[grepl(reg_string,names(df))]

  
df_feel<-melt(df[,..hap_col],id.vars = c("id"))[,variable:=gsub("^.*_","",variable)]

df_feel<-df_feel[,value:=ifelse(value %in% dk_vals,NA,
                        ifelse(value %in% "Yes",1,0))
           ][,any_neg:=ifelse(variable %in% c("Stressed","Lonely","Worried","Sad"),1,0)
             ][,any_pos:=ifelse(variable %in% c("Happy","Safe","Calm","Energetic","Excited"),1,0)
               ][,any_bored:=ifelse(variable=="Bored",1,0)]

df_sent<-df_feel[value==1][,lapply(.SD,function(x){
  ifelse(sum(x)>0,1,0)
  }),by=.(id),.SDcols=c("any_neg","any_pos","any_bored")]

df<-merge(df,df_sent)

```

```{r, child='W:/CCO-WORKING-FS/Projects/big ask survey/analysis/markdown/child docs/navigation_child_doc.rmd'}


```

<script src="extra_js.js"></script>

## `r params$pg`

### Summary

<h3>Key stats</h3>
<div class="stat-boxes">

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

</div>

<div class="row"></div>



<h3>About this data</h3>

INTRO TEXT

### Overall rates

<h3>What do children think is important for their future></h3>

```{r}
dat<-table_f("")[,.(c=sum(wt)),by=.(variable,value)][,perc:=round(c/sum(c),2)*100,by=.(variable)][value==1][,.(variable,perc)]

ggplot(dat,
       aes(x=reorder(variable,perc),y=perc))+
  geom_col(fill="light blue",colour="grey20")+coord_flip()+geom_text(aes(label=paste0(perc,"%")),hjust=1)+
  theme_bw()+xlab("")+ylab("% of 6-8 yr olds")

```