---
params:
  section: "abc"
  pg: "abc"
  var: "abc"
title: "`r paste0(params$section,': ',params$pg)`"
output: 
 html_document: 
   self_contained: no
   mathjax: null
   highlight: null
   fig_width: 10
   theme: null
   template: "../../CCO_template_html.html"
---

```{r, include=F}
knitr::opts_chunk$set(echo = F, warning=F,message = F) # add chunk options
```

<link rel="stylesheet" href="../../styles.css" type="text/css" />

```{r, results='asis'}

## Add breadcrumbs navigation

cat(paste0(
'<nav>
<ol>
<li class="breadcrumb"><a href="../../index.html">Home</a></li>
<li class="breadcrumb"><a href="',params$var,'_index.html">',params$section,'</a></li>
<li class="breadcrumb">',params$pg,'</li>
</ol>
</nav>'
))

```

<script src="extra_js.js"></script>

<h4>Approach to creating groups</h4>

<h4>Resulting groups with similar combinations</h4>

```{r}

# Chunk aims to import segmentation model - note model defined based on code in segmentation_template_doc


 # mod = marker for which segmentation to import, y = title to use in chart below
if(params$var=="9-17_happy"){

 mod<-"happy"

y<-"Children are unhappy with x\nin their current life"
}else if(params$var=="9-17_important"){

mod<-"important"
y<-"Children think x is\nimportant for their future"

}else if(params$var=="9-17_worry"){

mod<-"worry"

y<-"Children are worried about x\nfor the future"

}


# replace q_lookup with cluster lookup object - in essence changes outcome labels to be cluster names instead of happiness/future priorities/worries questions
q_lookup<-q_lookup_clust

target_vals<-c("Yes") # amend target levels

search_str_orig<-search_str # save original search string

search_str<-"cluster_" # change search string to be cluster variables

col1<-"Cluster" # amend col1 variable

table_f<-function(x,df_use=df){ # redefine table_f function to use segments as outcome
  
  x<-unlist(strsplit(x,"[|]"))
  
  reg<-paste0("^",x,"$")
  
  reg_string<-paste0("^id$|cluster_|^wt$|",paste0(reg,collapse="|"))
  hap_col<-names(df_use)[grepl(reg_string,names(df_use))]
  
  hap_col<-hap_col[!grepl("dont want to",hap_col)]
  
df_la<-melt(df_use[,..hap_col],id.vars = c("id",x,"wt"))[!is.na(value)][,variable:=plyr::mapvalues(variable,
                                                                                    q_lookup$var,
                                                                                    q_lookup$label)]

df_la[,value:=ifelse(value %in% target_vals,1,0)
           ]
}

# Read in segmentation model depending on mod object

if(mod=="happy"){
  clust_mod<-readRDS("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/happy_clust.rds")
  
}else if(mod=="important"){
  clust_mod<-readRDS("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/important_clust.rds")
}else if(mod=="worry"){
  
  clust_mod<-readRDS("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/worry_clust.rds")
}

df<-merge(df,clust_mod$clust_wide,by="id",all.x=T) # append segments to df object

## Slightly convoluted way of naming segments - sorry but it was late when I did this bit

plot_df<-ggplot_build(clust_mod$plots[[1]]) # turn plot into data frame

plot_df<-plot_df$plot$data # get original data for plot

plot_df$clust<-plyr::mapvalues(plot_df$clust,gsub("cluster_","",q_lookup$var),q_lookup$label) # rename clusters

plot_df$clust_lb<-paste0(plot_df$clust,"\n",plot_df$perc_clust,"%")

# Remake plot

clust_plot<-ggplot(plot_df,aes(x=variable,y=diff2))+geom_col(fill="light blue",colour="grey20")+
  facet_wrap(~clust_lb)+coord_flip()+scale_y_continuous(limits=c(-max(plot_df$diff2)*1.1,max(plot_df$diff2)*1.1))+
  #geom_text(aes(label=lb))+
  xlab(y)+ylab("\nPercentage point difference to\naverage rate")+
  theme_bw()
```

```{r, fig.width=10, fig.height=10}

# print plot with renamed clusters 
# div below defines picker to switch between child chars/vuln chars/area chars etc
# Note rest of code reruns child docs with segmentation as outcome. refer to annotated child documents

clust_plot

```


<div class="picker-group">
<label>Explore characteristics of these groups</label>
<select id="segUnhappy_picker">
<option value="seg_childChars">Children's demographics</option>
<option value="seg_maps">Differences by local area</option>
<option value="seg_areaChars">Differences by area characteristics</option>
<option value="seg_disad">Differences by vulnerable groups</option>
</select>
<button class="picker_button" onclick="picker_f('segUnhappy_picker','segUnhappy')">Go</button>
</div>

<div id="seg_childChars" class="sect segUnhappy">

```{r,child='W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\markdown\\child docs\\child_chars_child_doc.rmd'}

```

</div>

<div id="seg_maps" class="sect segUnhappy">

```{r,child='W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\markdown\\child docs\\map_child_doc.rmd'}

```

</div>

<div id="seg_areaChars" class="sect segUnhappy">

```{r,child='W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\markdown\\child docs\\area_chars_child_doc.rmd'}

```

</div>

<div id="seg_disad" class="sect segUnhappy">

```{r,child='W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\markdown\\child docs\\disad_child_doc.rmd'}

```

</div>

