---
params:
  section: "abc"
  pg: "abc"
  var: "abc"
title: "Children in youth custody"
output: 
 html_document: 
   self_contained: no
   mathjax: null
   highlight: null
   fig_width: 10
   theme: null
   template: "../../CCO_template_html.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,warning=F,message=F)
```

<link rel="stylesheet" href="../../styles.css" type="text/css" />

<a href="../../index.html">Home</a></li>

```{r}

# import most packages needed
require(readxl)
require(data.table)
require(dplyr)
require(ggplot2)
require(reactable)
require(htmltools)
require(tippy)

age_grp<-NULL # set age_grp variable - marker for 9-17s/6-8


df_all<-readRDS("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/survey data/final data/9-17_weighted.rds")

df_all<-df_all[dem_age_clean %in% c("15","16","17")]

```

```{r yoi_cleaning}

yoi_files<-list.files("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\survey data\\YOI data",pattern="[.]csv",
                      full.names=T)


 stem<-"W:/CCO-WORKING-FS/Projects/big ask survey/analysis/"

  varLookup<-as.data.table(readxl::read_excel(paste0(stem,"aux data/13-17_varlookup.xlsx"),"varnames"))
valLookup<-as.data.table(readxl::read_excel(paste0(stem,"aux data/13-17_varlookup.xlsx"),"values"))

df<-rbindlist(lapply(yoi_files, function(x){
  
  df<-fread(x)
  
df<-df[,lapply(.SD,function(y){
  gsub("[']|[|]+","",y)})
  ][,rw:=seq_len(.N)
    ][,id:=paste0(
      gsub("^.*[/]|[.]csv","",x),"_",rw
    )][,wt:=1]

df
  
})
)

### Support
df_supp<-df[,.(id,dem_support)]

df_supp<-df_supp[,dem_support:=gsub("My relative[(]s[)] e[.]g[.][,] grandparents[,] aunt[,] uncle","Relatives",dem_support)]

df_supp<-df_supp[,dem_support:=gsub("A counsellor[,] therapist or other health care worker","A counsellor therapist or other health care worker",dem_support)]


supp_vals<-sort(unique(unlist(strsplit(df_supp$dem_support,", "))))

supp_look<-data.table(orig=supp_vals,out_val=ifelse(!supp_vals %in% valLookup$dem_support,"Other",supp_vals))

cols<-paste0("dem_support_",unique(supp_look$out_val))

df_supp_wide<-Reduce(function(x,y) merge(x,y,by="id"),lapply(cols,function(x){
  letter<-gsub("dem_support_","",x)
  
  out<-data.table(id=df_supp$id,v=ifelse(grepl(letter,df_supp$dem_support),"Yes","No"))
  
  names(out)[2]<-x
  out
})
)

### important

df_imp<-df[,.(id,q2_important)]

df_imp<-df_imp[,q2_important:=gsub("My relative[(]s[)] e[.]g[.][,] grandparents[,] aunt[,] uncle","Relatives",q2_important)]

df_imp<-df_imp[,q2_important:=gsub("A counsellor[,] therapist or other health care worker","A counsellor therapist or other health care worker",q2_important)]


supp_vals<-sort(unique(unlist(strsplit(df_imp$q2_important,", "))))

supp_look<-data.table(orig=supp_vals,out_val=ifelse(!supp_vals %in% valLookup$q2_important,"Other",supp_vals))

cols<-paste0("q2_important_",unique(supp_look$out_val))

df_imp_wide<-Reduce(function(x,y) merge(x,y,by="id"),lapply(cols,function(x){
  letter<-gsub("q2_important_","",x)
  
  out<-data.table(id=df_imp$id,v=ifelse(grepl(letter,df_imp$q2_important),"Yes","No"))
  
  names(out)[2]<-x
  out
})
)

## Worry

df_worry<-df[,.(id,q3_worry)]

df_worry<-df_worry[,q3_worry:=gsub("My relative[(]s[)] e[.]g[.][,] grandparents[,] aunt[,] uncle","Relatives",q3_worry)]

df_worry<-df_worry[,q3_worry:=gsub("A counsellor[,] therapist or other health care worker","A counsellor therapist or other health care worker",q3_worry)]


supp_vals<-sort(unique(unlist(strsplit(df_worry$q3_worry,", "))))

supp_look<-data.table(orig=supp_vals,out_val=ifelse(!supp_vals %in% valLookup$q3_worry,"Other",supp_vals))

cols<-paste0("q3_worry_",unique(supp_look$out_val))

df_worry_wide<-Reduce(function(x,y) merge(x,y,by="id"),lapply(cols,function(x){
  letter<-gsub("q3_worry_","",x)
  
  out<-data.table(id=df_worry$id,v=ifelse(grepl(letter,df_worry$q3_worry),"Yes","No"))
  
  names(out)[2]<-x
  out
})
)

df<-Reduce(function(x,y) merge(x,y,all.x=T,by="id"),list(df,df_supp_wide,df_imp_wide,df_worry_wide))



for(x in names(valLookup)[!names(valLookup) %in% c("dem_support","q2_important","q3_worry")]){
  col<-valLookup[[x]]
  vals<-col[!is.na(col)]
  
  if(length(vals)>0){
    
    vals<-gsub("[']","",vals)
    
    v_out<-paste0(x,"_clean")
    
    df<-df[,(v_out):=ifelse(get(x) %in% vals,get(x),"Other")]
    
  }
  
  
}

```

## How happy are children with their lives currently?

```{r}

stem<-"W:/CCO-WORKING-FS/Projects/big ask survey/analysis/survey data/cleaned data/" # file path for cleaned data

search_str<-"happy.*clean" # string identifying outcome variables

dk_vals<-c("I don't know","Not applicable","dont know","I dont want to say") # values to treat as missing

target_vals<-c("Unhappy","Very unhappy","sad") # variables to recode to being 1


table_f<-function(x,df_use=df){ # function to reshape data to long format and recode outcome variables
  
  x<-unlist(strsplit(x,"[|]")) # if more than one grouping variable specified, split by | delimiter
  
  reg<-paste0("^",x,"$") # add beginning and end of word markers to ensure no accidental matching of variables
  
  reg_string<-paste0("^id$|happy.*clean|^wt$|",paste0(reg,collapse="|")) # combine into single regex to get outcome and grouping variables
  hap_col<-names(df_use)[grepl(reg_string,names(df_use))] # get column names matching regex


  # select relevant columns, reshape to long format... one row per indivual per outcome.... and rename outcome variables

df_la<-melt(df_use[,..hap_col],id.vars = c("id",x,"wt"))[,variable:=plyr::mapvalues(variable,
                                                                                    q_lookup$var,
                                                                                    q_lookup$label)]

# recode dks etc as NA and those in target vals as 1 else 0
df_la[,value:=ifelse(value %in% dk_vals,NA,
                        ifelse(value %in% target_vals,1,0))
           ]
}

## import table helper functions from markdown functions script

source("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/scripts/markdown_functions.R",local=knitr::knit_global())
  
col1<-"% of children unhappy with..." # define column label for outcomes in tables

q_lookup<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_happy_q_lookup.csv") # lookup for happiness questions
q_lookup$var<-gsub("Option ","q1_happy_",q_lookup$var) # clean up lookup


```

```{r}

df_yoi<-rbind(table_f("")[,yoi:="Children in youth custody"],
      table_f("",df_all)[,yoi:="Other 15-17 yr olds"])[,yoi:=factor(yoi,c("Other 15-17 yr olds",
                                                                                    "Children in youth custody"))]

two_way_tb_f(df_yoi,"yoi","Children in youth custody vs Not",col1)

```

## What do children think is important for their future?

```{r}
target_vals<-"Yes" # value to be coded as 1

dk_vals<-""

col1<-"% of children that think x is important..."

search_str<-"important_" # string to match outcomes in column names

table_f<-function(x,df_use=df){ # table_f function redefined to account for differences between important and happiness question structure
  
  x<-unlist(strsplit(x,"[|]"))
  
  reg<-paste0("^",x,"$")
  
  reg_string<-paste0("^id$|important_|^wt$|",paste0(reg,collapse="|"))
  hap_col<-names(df_use)[grepl(reg_string,names(df_use))]
  
  hap_col<-hap_col[!grepl("dont want to",hap_col)]
  
df_la<-melt(df_use[,..hap_col],id.vars = c("id",x,"wt"))[,variable:=plyr::mapvalues(variable,
                                                                                    q_lookup$var,
                                                                                    q_lookup$label)]

df_la[,value:=ifelse(value %in% target_vals,1,0)
           ]
}

q_lookup<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_important_q_lookup.csv")
q_lookup<-q_lookup[!grepl("dont want",var)]

```

```{r}

df_yoi<-rbind(table_f("")[,yoi:="Children in youth custody"],
      table_f("",df_all[`q2_important_I dont want to say` %in% c(NA,"No")])[,yoi:="Other 15-17 yr olds"])[,yoi:=factor(yoi,c("Other 15-17 yr olds",
                                                                                    "Children in youth custody"))]

two_way_tb_f(df_yoi,"yoi","Children in youth custody vs Not",col1)

```

## What do children worry about for their future?

```{r}
target_vals<-"Yes"

dk_vals<-""

search_str<-"worry_"

col1<-"% of children that are worried about x..."

table_f<-function(x,df_use=df){
  
  x<-unlist(strsplit(x,"[|]"))
  
  reg<-paste0("^",x,"$")
  
  reg_string<-paste0("^id$|worry_|^wt$|",paste0(reg,collapse="|"))
  hap_col<-names(df_use)[grepl(reg_string,names(df_use))]
  
  hap_col<-hap_col[!grepl("dont want to",hap_col)]
  
df_la<-melt(df_use[`q3_worry_I dont want to say` %in% c(NA,"No")][,..hap_col],id.vars = c("id",x,"wt"))[,variable:=plyr::mapvalues(variable,
                                                                                    q_lookup$var,
                                                                                    q_lookup$label)]

df_la[,value:=ifelse(value %in% target_vals,1,0)
           ]
}

q_lookup<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_worry_q_lookup.csv")
q_lookup<-q_lookup[!grepl("dont want",var)]

```

```{r}

df_yoi<-rbind(table_f("")[,yoi:="Children in youth custody"],
      table_f("",df_all[`q2_important_I dont want to say` %in% c(NA,"No")])[,yoi:="Other 15-17 yr olds"])[,yoi:=factor(yoi,c("Other 15-17 yr olds",
                                                                                    "Children in youth custody"))]

two_way_tb_f(df_yoi,"yoi","Children in youth custody vs Not",col1)

```