---
params:
  section: "abc"
  pg: "abc"
  var: "abc"
title: "`r paste0(params$section,': ',params$pg)`"
output: 
 html_document: 
   self_contained: no
   mathjax: null
   highlight: null
   fig_width: 10
   theme: null
   template: "../../CCO_template_html.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning=F,message = F)

require(readxl)
require(data.table)
require(dplyr)
require(ggplot2)
require(reactable)
require(htmltools)
require(tippy)

age_grp<-NULL

stem<-"W:/CCO-WORKING-FS/Projects/big ask survey/analysis/survey data/cleaned data/"

target_vals<-"Yes"

dk_vals<-""

search_str<-"worry_"

col1<-"% of children that are worried about x..."

table_f<-function(x,df_use=df){
  
  x<-unlist(strsplit(x,"[|]"))
  
  reg<-paste0("^",x,"$")
  
  reg_string<-paste0("^id$|worry_|^wt$|",paste0(reg,collapse="|"))
  hap_col<-names(df_use)[grepl(reg_string,names(df_use))]
  
  hap_col<-hap_col[!grepl("dont want to",hap_col)]
  
df_la<-melt(df_use[`q3_worry_I dont want to say` %in% c(NA,"No")][,..hap_col],id.vars = c("id",x,"wt"))[,variable:=plyr::mapvalues(variable,
                                                                                    q_lookup$var,
                                                                                    q_lookup$label)]

df_la[,value:=ifelse(value %in% target_vals,1,0)
           ]
}

source("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/scripts/markdown_functions.R",local=knitr::knit_global())
```

<link rel="stylesheet" href="../../styles.css" type="text/css" />

```{r}

df<-readRDS("W:/CCO-WORKING-FS/Projects/big ask survey/analysis/survey data/final data/9-17_weighted.rds")

#imd<-fread(file="W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/imd2019lsoa.csv")[Measurement=="Decile"]

imd<-fread(file="W:/CCO-WORKING-FS/Projects/big ask survey/analysis/aux data/idaci.csv")

df<-df[,`q3_worry_Im not worried about anything`:=ifelse(is.na(`q3_worry_Im not worried about anything`) & grepl("not worried",q3_worry),"Yes",ifelse(is.na(`q3_worry_Im not worried about anything`),"No",`q3_worry_Im not worried about anything`))]

df<-df[`q3_worry_I dont want to say` %in% c(NA,"No")]

q_lookup<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_worry_q_lookup.csv")
q_lookup<-q_lookup[!grepl("dont want",var)]

q_lookup_hap<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_happy_q_lookup.csv")
q_lookup_hap$var<-gsub("Option ","q1_happy_",q_lookup_hap$var)

q_lookup_imp<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_important_q_lookup.csv")
q_lookup<-q_lookup[!grepl("dont want",var)]

hap_col<-names(df)[grepl("^id$|worry_|^wt$",names(df))]

q_lookup_clust<-fread("W:\\CCO-WORKING-FS\\Projects\\big ask survey\\analysis\\aux data\\13-17_worry_cluster_q_lookup.csv")


```


```{r, child='W:/CCO-WORKING-FS/Projects/big ask survey/analysis/markdown/child docs/navigation_child_doc.rmd'}


```

<script src="extra_js.js"></script>

<h3>Key stats
<div class="stat-boxes">

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-lg-3">
<div class="stat">
<div class="stat-box-outer">
<div class="stat-box-inner">
<p class="figure">Key stat</p>
</div>
</div>
</div>
</div>

</div>

<div class="row"></div>

<h3>About this data

INTRO TEXT

<h3>What are children worried about for their future?</h3>

```{r}
dat<-table_f("")[!grepl("dont",variable)][,.(c=sum(wt)),by=.(variable,value)][,perc:=round(c/sum(c),2)*100,by=.(variable)][value==1 & !grepl("Other",variable)][,.(variable,perc)]

ggplot(dat,
       aes(x=reorder(variable,perc),y=perc))+
  geom_col(fill="light blue",colour="grey20")+coord_flip()+geom_text(aes(label=paste0(perc,"%")),hjust=1)+
  theme_bw()+xlab("")+ylab("% of 9-17 yr olds")

```

<h3>How many things are children worried about regarding their future?</h3>

```{r}

# Copied over 9-17 code, table shows up with zero - Chunk to make table of number of aspects of life children are worried about - 


df_worry<-melt(df[,..hap_col],id.vars = c("id","wt")) # convert to long format

# recode outcomes and get number of worry items for each person
dat<-copy(df_worry)[,value:=ifelse(value %in% dk_vals,NA,
                        ifelse(value %in% target_vals,1,0))
           ][!is.na(value)
             ][,.(tot=sum(value,na.rm=T)),by=.(id,wt)]

# Work out cumulative percentages by count of worry items
tb<-dat[,.(c=sum(wt)),by=.(tot)
    ][,perc:=c/sum(c)][order(-tot)
                       ][,cum_perc:=cumsum(perc)
                         ][,cum_perc:=round(ifelse(tot==0,perc,cum_perc),3)*100
                           ][,tot:=ifelse(tot==0,"0",ifelse(tot==max(tot),"All",paste0(tot,"+")))
                             ][,.(tot,cum_perc)
                               ]

# create table
names(tb)<-c("Number of things that children are worried about","% of respondents")

div(reactable(tb,
             columns=list(`Number of things that children are worried about`=colDef(),`% of respondents`=colDef()),
    pagination = F,
    fullWidth = T,
    bordered = T,
    resizable = T,
    searchable = F,
    showSortable = T,
    language = reactableLang(searchPlaceholder = "Search table...",searchLabel = "")),
    downloadthis::download_this(tb,output_name ="big_ask_download",output_extension = ".xlsx")
)






```